Periodic Customer Spawning
mikestiers/Baristapocalypse pull request #16
Opened 2023-06-01 00:26 UTC by rjcayaco

2023-06-01 19:25 UTC, teanbes requested changes
which PR should we merge?

2023-06-01 19:25 UTC, teanbes requested changes
which PR should we merge?

2023-06-03 19:24 UTC, jeffrey-tong approved these changes

2023-06-03 19:26 UTC, jeffrey-tong commented on Assets/Development/Scripts/AI/C_Manager.cs
> +    public Transform Counter;
Please change these to [SerializeField] private if possible

2023-06-03 19:26 UTC, teanbes approved these changes

2023-06-03 19:27 UTC, jeffrey-tong reviewed
A lot of your variable declarations are public, please change those to [SerializeField] private where possible, and try to make more of the private if u can. If you cant get those changes done by tuesday that's ok.

2023-06-03 19:28 UTC, merged